Align API version of components with API version in sfdx-project.json
davidbrowaeys/DXB pull request #26
Opened 2023-09-20 16:16 UTC by OlivierBrabanders

2023-09-21 06:53 UTC, davidbrowaeys commented
Very good 2 things to add : 

- We need to be able to filter by metadata type only. So maybe we can add something like  --metadatatype param. 
example--m "ApexClass". If flag is not present then we need to process for all. 

- Sometimes, we want to be able to specify a api version on a specific class. So we need to maintain an exclusion list so that it will never process those. To do so I am proposing to add a new attribute as apiAlignmentExclusion under dxb in the sfdx-plugin
example: 
`"apiAlignmentExclusion": ["force-app/main/default/classes/MyBadClass.cls-meta.xml","force-app/main/default/classes/SuperbadClass.cls-meta.xml"]`

2023-09-21 06:54 UTC, davidbrowaeys requested changes
Very good 2 things to add :

We need to be able to filter by metadata type only. So maybe we can add something like --metadatatype param.
example--m "ApexClass". If flag is not present then we need to process for all.

Sometimes, we want to be able to specify a api version on a specific class. So we need to maintain an exclusion list so that it will never process those. To do so I am proposing to add a new attribute as apiAlignmentExclusion under dxb in the sfdx-plugin
example:
"apiAlignmentExclusion": ["force-app/main/default/classes/MyBadClass.cls-meta.xml","force-app/main/default/classes/SuperbadClass.cls-meta.xml"]

2023-09-22 06:51 UTC, davidbrowaeys commented on src/commands/dxb/api/align.ts
> +      multiple: true
nice

2023-09-22 09:01 UTC, OlivierBrabanders commented
Ready for review David!

2023-09-25 14:02 UTC, merged